const data = {
  fragrances: require('../assets/images/Category/fragrance.png'),
  skincare: require('../assets/images/Category/skincare.png'),
  groceries: require('../assets/images/Category/groceries.png'),
  'home-decoration': require('../assets/images/Category/home-decoration.png'),
  furniture: require('../assets/images/Category/furniture.png'),
  tops: require('../assets/images/Category/tops.png'),
  'womens-dresses': require('../assets/images/Category/womens-dresses.png'),
  'womens-shoes': require('../assets/images/Category/womens-shoes.png'),
  'mens-shirts': require('../assets/images/Category/mens-shirts.png'),
  'mens-shoes': require('../assets/images/Category/mens-shoes.png'),
  'mens-watches': require('../assets/images/Category/mens-watches.png'),
  'womens-watches': require('../assets/images/Category/womens-watches.png'),
  'womens-bags': require('../assets/images/Category/womens-bags.png'),
  'womens-jewellery': require('../assets/images/Category/womens-jewellery.png'),
  sunglasses: require('../assets/images/Category/sunglasses.png'),
  automotive: require('../assets/images/Category/automotive.png'),
  motorcycle: require('../assets/images/Category/motorcycle.png'),
  lighting: require('../assets/images/Category/lighting.png'),
};
export default data;
