const Strings = {
  enter: 'Enter',
  login: 'Login',
  welcome: 'Welcome!',
  edit: 'Edit',
  add: 'Add',
  view: 'View',
  dollar: '$',
  details: 'Details',
  name: 'Name',
  password: 'Password',
  mobileNo: 'Mobile Number',
  address: 'Address',
  pincode: 'Pincode',
  city: 'City',
  state: 'State',
  email: 'email',
  emptyCart: 'Empty Cart',
  totalAmount: 'Total Amount',
  categories: 'Categories',
  product: 'Product',
  search: 'Type to Search',
  incorrectInput: 'Incorrect Input',
  checkfield: 'Check all fields again',
  credentials: 'Credentials',
  valid: 'valid',
  invalid: 'Invalid',
  tryAgain: 'Please Try Again.',
  checkCredentials: 'Please check your Credentials.',
  outOfStock: 'Out Of Stock',
  noStock: 'The Item is Out of Stock.',
};
export default Strings;
