const Strings = {
  logout: 'Logout',
  success: 'You have successfully ordered.',
  order: 'in this order.',
  saved: 'You Saved',
  userExist: 'User Exist',
  pleaseLogin: 'This user already exists. Please login with same.',
  noDeliveryDetails: 'No Delivery Details',
  delivery: "You haven't filled Account Details. Do you want to Enter Details?",
  fewLeft: 'Left only',
  stock: 'In Stock',
  specialPrice: 'Special Price',
  enter: 'Enter',
  signup: 'Signup',
  signin: 'Sign-In',
  login: 'Login',
  welcome: 'Welcome!',
  item: 'Item',
  priceDetails: 'Price Details',
  off: 'off',
  edit: 'Edit',
  add: 'Add',
  view: 'View',
  dollar: '$',
  details: 'Details',
  name: 'Name',
  password: 'Password',
  confirmPasswordError: 'Password and Confirm Password did not match.',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot Password?',
  alreadyAccount: 'Already have an Account?',
  noAccount: "Don't have an Account?",
  mobileNo: 'Mobile Number',
  address: 'Address',
  pincode: 'Pincode',
  city: 'City',
  state: 'State',
  email: 'email',
  emptyCart: 'Empty Cart',
  addToCart: 'Add to Cart',
  totalAmount: 'Total Amount',
  discount: 'Discount',
  categories: 'Categories',
  product: 'Product',
  search: 'Type to Search',
  incorrectInput: 'Incorrect Input',
  checkfield: 'Check all fields again',
  credentials: 'Credentials',
  valid: 'valid',
  invalid: 'Invalid',
  tryAgain: 'Please Try Again.',
  checkCredentials: 'Please check your Credentials.',
  outOfStock: 'Out Of Stock',
  noStock: 'The Item is Out of Stock.',
  proceed: 'Add Items to proceed.',
  userNotExist: 'User does not Exist',
  pleaseSignup: 'Create an account in Signup.',
};
export default Strings;
